"use client";

// Terms on the phone: the industry packs (Chinese–English; name and count,
// tap to turn on, 详情 for the list), terms generated by AI for the
// meeting's languages ("a=b=c"), and your own terms. Same state as the
// desktop TermsPanel.

import { useEffect, useState } from "react";
import { Check, Loader2, Plus, Sparkles, X } from "lucide-react";
import { INDUSTRY_PRESETS, combineTerms, presetLabel, splitTermInput } from "@/lib/contextTerms";
import { useLanguageName, useT } from "@/lib/i18n";
import { SONIOX_LANGUAGES } from "@/types/bilingual";
import { BottomSheet, SectionTitle, useLangNames } from "./parts";

interface PhoneTermsProps {
  onTermsTextChange: (text: string) => void;
  selectedPresets: Set<string>;
  onSelectedPresetsChange: (presets: Set<string>) => void;
  customTerms: string[];
  onCustomTermsChange: (terms: string[]) => void;
  isRecording: boolean;
  // The meeting's languages, the default for AI suggestions
  meetingLanguages: string[];
}

const MAX_DESCRIPTION = 500;
const MAX_LANGUAGES = 5;

export default function PhoneTerms({
  onTermsTextChange,
  selectedPresets,
  onSelectedPresetsChange,
  customTerms,
  onCustomTermsChange,
  isRecording,
  meetingLanguages,
}: PhoneTermsProps) {
  const t = useT();
  const [input, setInput] = useState("");
  const [details, setDetails] = useState<string | null>(null);

  // Keep the combined list in the page state, as the desktop panel does
  useEffect(() => {
    onTermsTextChange(combineTerms(selectedPresets, customTerms).join(", "));
  }, [selectedPresets, customTerms, onTermsTextChange]);

  const toggle = (key: string) => {
    const next = new Set(selectedPresets);
    if (next.has(key)) next.delete(key);
    else next.add(key);
    onSelectedPresetsChange(next);
  };

  const addTerms = (terms: string[]) => {
    const next = [...customTerms];
    for (const term of terms) {
      if (!next.some((x) => x.toLowerCase() === term.toLowerCase())) next.push(term);
    }
    if (next.length !== customTerms.length) onCustomTermsChange(next);
  };

  const addTyped = () => {
    addTerms(splitTermInput(input));
    setInput("");
  };

  const detailPreset = details ? INDUSTRY_PRESETS[details] : null;

  return (
    <div className="pb-2">
      <SectionTitle>{t("ph_term_packs")}</SectionTitle>
      <p className="mb-2 text-xs leading-snug text-gray-600">{t("ph_packs_note")}</p>
      <ul className="space-y-2">
        {Object.entries(INDUSTRY_PRESETS).map(([key, preset]) => {
          const on = selectedPresets.has(key);
          return (
            <li
              key={key}
              className={`flex items-center rounded-2xl border transition-colors ${
                on ? "border-foreground bg-muted/50" : "border-border"
              }`}
            >
              <button
                type="button"
                role="switch"
                aria-checked={on}
                onClick={() => toggle(key)}
                className="flex min-w-0 flex-1 items-center gap-3 py-3 pl-4 text-left"
              >
                <span
                  className={`grid size-6 shrink-0 place-items-center rounded-full border ${
                    on ? "border-foreground bg-foreground text-background" : "border-gray-300"
                  }`}
                  aria-hidden
                >
                  {on && <Check className="size-4" />}
                </span>
                <span className="min-w-0">
                  <span className="block truncate text-base font-semibold text-foreground">
                    {presetLabel(key, preset.label, t)}
                  </span>
                  <span className="block text-xs text-gray-600">
                    {t("ph_n_terms", { n: preset.terms.length })} · {t("ph_pack_zh_en")}
                  </span>
                </span>
              </button>
              <button
                type="button"
                onClick={() => setDetails(key)}
                className="shrink-0 px-4 py-3 text-sm font-medium text-blue-700"
              >
                {t("ph_details")}
              </button>
            </li>
          );
        })}
      </ul>

      <AiTerms meetingLanguages={meetingLanguages} onAdd={addTerms} />

      <SectionTitle>{t("ph_custom_terms")}</SectionTitle>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          addTyped();
        }}
        className="flex gap-2"
      >
        <input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          // Typed but not added (closed the sheet): keep it
          onBlur={() => {
            if (input.trim()) addTyped();
          }}
          placeholder={t("ph_custom_placeholder")}
          enterKeyHint="done"
          autoCapitalize="off"
          autoCorrect="off"
          className="h-11 min-w-0 flex-1 rounded-xl border border-input bg-background px-3 text-base outline-none focus:border-ring"
        />
        <button
          type="submit"
          disabled={!input.trim()}
          className="inline-flex h-11 shrink-0 items-center gap-1 rounded-xl bg-foreground px-4 text-[15px] font-semibold text-background disabled:opacity-40"
        >
          <Plus className="size-4" aria-hidden />
          {t("ph_add")}
        </button>
      </form>
      <p className="mt-2 text-xs leading-snug text-gray-600">{t("ph_custom_hint")}</p>
      {customTerms.length > 0 && (
        <ul className="mt-3 flex flex-wrap gap-2">
          {customTerms.map((term, i) => (
            <li key={`${term}-${i}`} className="inline-flex items-center gap-1 rounded-full bg-muted py-1 pl-3 pr-1 text-sm">
              <span className="max-w-[70vw] truncate">{term.split("=").join(" = ")}</span>
              <button
                type="button"
                aria-label={t("ph_remove_term", { name: term })}
                onClick={() => onCustomTermsChange(customTerms.filter((_, j) => j !== i))}
                className="grid size-6 place-items-center rounded-full text-gray-600 hover:bg-background"
              >
                <X className="size-3.5" />
              </button>
            </li>
          ))}
        </ul>
      )}
      <p className="mt-4 text-xs text-gray-600">{isRecording ? t("terms_effect_next") : t("terms_effect_start")}</p>

      {/* A pack's terms */}
      <BottomSheet
        open={detailPreset !== null}
        onOpenChange={(o) => !o && setDetails(null)}
        title={details && detailPreset ? presetLabel(details, detailPreset.label, t) : ""}
        tall
      >
        <p className="mb-2 text-xs text-gray-600">
          {detailPreset && t("ph_n_terms", { n: detailPreset.terms.length })} · {t("ph_pack_zh_en")}
        </p>
        <ul>
          {detailPreset?.terms.map((term) => {
            const [a, ...rest] = term.split("=");
            return (
              <li key={term} className="flex gap-3 border-b border-border py-2 text-[15px] last:border-b-0">
                <span className="min-w-0 flex-1 text-foreground">{a}</span>
                {rest.length > 0 && <span className="min-w-0 flex-1 text-gray-600">{rest.join(" = ")}</span>}
              </li>
            );
          })}
        </ul>
      </BottomSheet>
    </div>
  );
}

// Describe the meeting, pick its languages, get terms in each language
// (also in the desktop terms panel)
export function AiTerms({ meetingLanguages, onAdd }: { meetingLanguages: string[]; onAdd: (terms: string[]) => void }) {
  const t = useT();
  const { native } = useLangNames();
  const langName = useLanguageName();
  const [languages, setLanguages] = useState<string[]>(meetingLanguages.slice(0, MAX_LANGUAGES));
  const [description, setDescription] = useState("");
  const [state, setState] = useState<"idle" | "loading" | "limit" | "failed" | "empty">("idle");
  const [results, setResults] = useState<string[] | null>(null);
  const [chosen, setChosen] = useState<Set<string>>(new Set());

  const generate = async () => {
    setState("loading");
    setResults(null);
    try {
      const res = await fetch("/api/terms/suggest", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ description: description.trim(), languages }),
      });
      if (res.status === 429) return setState("limit");
      if (!res.ok) return setState("failed");
      const { terms } = (await res.json()) as { terms: string[] };
      if (!terms?.length) return setState("empty");
      setResults(terms);
      setChosen(new Set(terms));
      setState("idle");
    } catch {
      setState("failed");
    }
  };

  const toggle = (term: string) => {
    const next = new Set(chosen);
    if (next.has(term)) next.delete(term);
    else next.add(term);
    setChosen(next);
  };

  return (
    <section className="mt-5 rounded-2xl border border-border p-4" data-ai-terms>
      <h3 className="flex items-center gap-1.5 text-base font-semibold text-foreground">
        <Sparkles className="size-4" aria-hidden />
        {t("ph_ai_title")}
      </h3>

      <p className="mt-3 text-xs font-medium text-gray-600">{t("ph_ai_languages")}</p>
      <div className="mt-1.5 flex flex-wrap gap-2">
        {languages.map((code) => (
          <span key={code} className="inline-flex items-center gap-1 rounded-full bg-muted py-1 pl-3 pr-1 text-sm">
            {native(code)}
            <button
              type="button"
              aria-label={t("ph_remove_language", { name: native(code) })}
              disabled={languages.length <= 1}
              onClick={() => setLanguages(languages.filter((c) => c !== code))}
              className="grid size-6 place-items-center rounded-full text-gray-600 hover:bg-background disabled:invisible"
            >
              <X className="size-3.5" />
            </button>
          </span>
        ))}
        {languages.length < MAX_LANGUAGES && (
          // A native list: the system picker on phones, a menu on desktop
          <label className="relative inline-flex items-center gap-1 rounded-full border border-dashed border-gray-300 px-3 py-1 text-sm text-blue-700">
            <Plus className="size-3.5" aria-hidden />
            {t("ph_add_language")}
            <select
              value=""
              onChange={(e) => e.target.value && setLanguages([...languages, e.target.value].slice(0, MAX_LANGUAGES))}
              aria-label={t("ph_add_language")}
              className="absolute inset-0 cursor-pointer opacity-0"
            >
              <option value="" />
              {SONIOX_LANGUAGES.filter((l) => !languages.includes(l.code)).map((l) => (
                <option key={l.code} value={l.code}>
                  {langName(l.code)}
                </option>
              ))}
            </select>
          </label>
        )}
      </div>

      <textarea
        value={description}
        onChange={(e) => setDescription(e.target.value.slice(0, MAX_DESCRIPTION))}
        placeholder={t("ph_ai_placeholder")}
        rows={3}
        className="mt-3 w-full resize-none rounded-xl border border-input bg-background px-3 py-2 text-base outline-none focus:border-ring"
      />
      <div className="mt-1 flex items-center justify-between gap-2">
        <span className="text-xs text-gray-600">{t("ph_ai_note")}</span>
        <span className="shrink-0 text-xs tabular-nums text-gray-500">
          {description.length}/{MAX_DESCRIPTION}
        </span>
      </div>

      <button
        type="button"
        onClick={generate}
        disabled={!description.trim() || state === "loading"}
        className="mt-3 inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-foreground text-[15px] font-semibold text-background disabled:opacity-40"
      >
        {state === "loading" ? <Loader2 className="size-4 animate-spin" /> : <Sparkles className="size-4" />}
        {state === "loading" ? t("ph_ai_generating") : results ? t("ph_ai_again") : t("ph_ai_generate")}
      </button>

      {(state === "limit" || state === "failed" || state === "empty") && (
        <p role="alert" className={`mt-2 text-sm ${state === "empty" ? "text-gray-700" : "text-red-700"}`}>
          {t(state === "limit" ? "ph_ai_limit" : state === "failed" ? "ph_ai_failed" : "ph_ai_empty")}
        </p>
      )}

      {results && (
        <>
          <ul className="mt-3">
            {results.map((term) => (
              <li key={term}>
                <button
                  type="button"
                  role="checkbox"
                  aria-checked={chosen.has(term)}
                  onClick={() => toggle(term)}
                  className="flex w-full items-center gap-3 border-b border-border py-2 text-left last:border-b-0"
                >
                  <span
                    className={`grid size-5 shrink-0 place-items-center rounded-md border ${
                      chosen.has(term) ? "border-foreground bg-foreground text-background" : "border-gray-300"
                    }`}
                    aria-hidden
                  >
                    {chosen.has(term) && <Check className="size-3.5" />}
                  </span>
                  <span className="min-w-0 flex-1 text-[15px] text-foreground">{term.split("=").join(" = ")}</span>
                </button>
              </li>
            ))}
          </ul>
          <button
            type="button"
            disabled={chosen.size === 0}
            onClick={() => {
              onAdd(results.filter((x) => chosen.has(x)));
              setResults(null);
              setDescription("");
            }}
            className="mt-3 inline-flex h-11 w-full items-center justify-center gap-1.5 rounded-xl border border-foreground text-[15px] font-semibold text-foreground disabled:opacity-40"
          >
            <Plus className="size-4" aria-hidden />
            {t("ph_ai_add_selected", { n: chosen.size })}
          </button>
        </>
      )}

    </section>
  );
}
